spring.application.name=order-service
server.port=8081
repository.type=jpa
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
openapi.contact.name=Jeexike
openapi.contact.email=dima@rozanov.org

spring:
liquibase:
change-log: classpath:/db/changelog/db.changelog-master.yaml

jpa:
hibernate:
ddl-auto: validate